//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by plugin.rc
//
#define VS_VERSION_INFO                 1
#define IDS_PLUGIN_SHORT_DESC           100
#define IDS_PLUGIN_LONG_DESC            101
#define IDS_PLUGIN_INFO                 102
#define IDS_MIN_SELECTION               103
#define IDD_DIALOG_TIMECAPSULE          104
#define IDS_DEFAULT_TITLE               105
#define IDS_SORT_MODE_EXIF              106
#define IDS_SORT_MODE_SELECTION         107
#define IDS_SORT_MODE_WEST_EAST         108
#define IDS_SORT_MODE_NORTH_SOUTH       109
#define IDS_SORTING_LABEL               110
#define IDS_SORT_MODE_EAST_WEST         111
#define IDS_SORT_MODE_SOUTH_NORTH       112
#define IDS_DISTANCE_DECIMAL_KM         113
#define IDS_DISTANCE_INTEGER_KM         114
#define IDS_DURATION_ZERO_HOURS         115
#define IDS_DURATION_DAYS_HOURS         116
#define IDS_DURATION_HOURS              117
#define IDS_LOCATION_FORMAT             118
#define IDS_SUMMARY_PICTURES            119
#define IDS_SUMMARY_EXTRAS              120
#define IDS_SUMMARY_DISTANCE_PREFIX     121
#define IDS_SUMMARY_DURATION_PREFIX     122
#define IDS_STORY_START_PREFIX          123
#define IDS_STORY_DESTINATION_PREFIX    124
#define IDS_STORY_SEPARATOR             125
#define IDS_STORY_LONGEST_HOP_PREFIX    126
#define IDS_DEFAULT_HEADER_TITLE        129
#define IDS_PROGRESS_INITIAL_PHASE      130
#define IDS_PROGRESS_INITIAL_DETAIL     131
#define IDS_PROGRESS_ANALYZE_PHASE      132
#define IDS_PROGRESS_ANALYZE_DETAIL     133
#define IDS_PROGRESS_LOOKUP_PHASE       134
#define IDS_PROGRESS_LOOKUP_DETAIL      135
#define IDS_PROGRESS_LOOKUP_DETAIL_GPS  136
#define IDS_PROGRESS_THROTTLE_PHASE     137
#define IDS_PROGRESS_THROTTLE_DETAIL    138
#define IDS_PROGRESS_RENDER_PHASE       139
#define IDS_PROGRESS_RENDER_DETAIL      140
#define IDS_PROGRESS_CANCEL_PHASE       141
#define IDS_PROGRESS_CANCEL_DETAIL      142
#define IDS_PROGRESS_CANCEL_MESSAGE     143
#define IDS_ERROR_PROGRESS_DIALOG       144
#define IDS_ERROR_PROGRESS_WORKER       145
#define IDS_PROGRESS_LOOKUP_DETAIL_NAME 146
#define IDS_PROGRESS_THROTTLE_DETAIL_NAME 147
#define IDC_EDIT_TITLE                  1000
#define IDC_COMBO_SORT_MODE             1001
#define IDC_CHECK_METADATA              1002
#define IDC_EDIT_THUMB_WIDTH            1003
#define IDC_EDIT_THUMB_HEIGHT           1004
#define IDC_EDIT_LOCATION_RADIUS        1005

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           148
#endif
#endif
